from elements import *

def message():
    clear_console()
    time.sleep(1)
    print_centered("My Pledge, My Wish")
    print("")
    print_centered("To: Lezzell F. Gumarang")
    print_centered("From: Justin T. Sotelo")
    time.sleep(3)
    print("")
    print_centered("You've found this letter. You've done some work to obtain it.")
    time.sleep(4)
    print_centered("This project. This project is not the gift.")
    time.sleep(2)
    print_centered("It is not a reward.")
    time.sleep(2)
    print_centered("It is not an attempt for any applause.")
    time.sleep(2)
    print_centered("It is not a special item.")
    time.sleep(2)
    print_centered("It was all for this. A message.")
    time.sleep(3)
    print_centered("Something not enough lines of code can properly say.")
    time.sleep(3)
    print_centered("Frankly, words cannot either.")
    time.sleep(3)
    print_centered("So, please read it all with undivided attention.")
    time.sleep(4)
    print("")
    print_centered("I pledge to remain with you.")
    time.sleep(2)
    print_centered("Not just for today.")
    time.sleep(1.5)
    print_centered("For as long as I shall remain on this earth.")
    time.sleep(4)
    print_centered("Though, it will come with costs.")
    time.sleep(3)
    print_centered("It will come with sacrifice.")
    time.sleep(2)
    print_centered("It will come with hardship.")
    time.sleep(2)
    print_centered("It will come with difficult facts to swallow.")
    time.sleep(3)
    print_centered("Yet, we remain. Firm.")
    time.sleep(4)
    print("")
    print_centered("I want to show you that you are loved for your beauties.")
    time.sleep(3)
    print_centered("I want to show you that you are loved for your faults.")
    time.sleep(3)
    print_centered("I want to show you that you are loved for your present self.")
    time.sleep(3)
    print_centered("I want to show you that you are loved for your being.")
    time.sleep(3)
    print_centered("I want to show you that you are loved for your interests.")
    time.sleep(3)
    print_centered("I want to show you that you are loved for your small, intricate details about you.")
    time.sleep(4)
    print_centered("I want to show you that you are loved for all your life.")
    time.sleep(3)
    print_centered("I want to show you that you are loved for all your previous mistakes.")
    time.sleep(3)
    print_centered("I want to show you that you are loved for all your desires and reasons for living.")
    time.sleep(3)
    print_centered("I want to show you that you are loved for all your efforts throughout your life.")
    time.sleep(3)
    print_centered("I want to show you that you are loved for all your worries and stess.")
    time.sleep(3)
    print_centered("I want to show you that love doesn't fade away when things get hard.")
    time.sleep(3)
    print_centered("I want to show you that love remains even when moments don't.")
    time.sleep(3)
    print_centered("I want to show you that you deserving of love.")
    time.sleep(3)
    print_centered("I want to show you that love remains loyal.")
    time.sleep(4)
    print_centered("So, please let me love you.")
    time.sleep(4)
    print_centered("For I want no other man to take my place.")
    time.sleep(5)
    print("")
    print_centered("You've been through so much. Especially at young ages.")
    time.sleep(4)
    print_centered("You stand despite all of the major challenges you've faced.")
    time.sleep(3)
    print_centered("For these efforts. I want to show you that you are very well capable of love.")
    time.sleep(4)
    print_centered("You've made mistakes in the past.")
    time.sleep(3)
    print_centered("Yet, it still doesn't push me away.")
    time.sleep(3)
    print_centered("So, let me wash your wounds.")
    time.sleep(3)
    print_centered("Let me pick you up when you fall.")
    time.sleep(3)
    print_centered("Let me bring you healthy love.")
    time.sleep(3)
    print_centered("Because I know you've been wanting a healthy love.")
    time.sleep(3)
    print_centered("So here, I offer myself to spend the rest of my life with you.")
    time.sleep(4)
    print_centered("I am a man of many faults.")
    time.sleep(2)
    print_centered("But I will do my best to make you happy.")
    time.sleep(3)
    print_centered("For your smile, your laughs in joy; they enchant me.")
    time.sleep(3)
    print_centered("Your warm hugs, your eyes when you smile; they uplift me.")
    time.sleep(5)
    print("")
    time.sleep(3)
    print_centered("So go ahead. Cry in my arms.")
    time.sleep(3)
    print_centered("Let yourself crumble before me.")
    time.sleep(3)
    print_centered("Soak my shirt in your tears.")
    time.sleep(2)
    print_centered("Open your heart to me.")
    time.sleep(4)
    print_centered("Tell me your fears.")
    time.sleep(5)
    print_centered("Tell me what burdens you.")
    time.sleep(5)
    print_centered("Tell me what makes your heart aches over.")
    time.sleep(5)
    print_centered("Tell me all that causes you to weary.")
    time.sleep(5)
    print_centered("Tell me things your heart finds hard to say.")
    time.sleep(5)
    print_centered("Cliing onto me, rest your head on my shoulders.")
    time.sleep(5)
    print_centered("Let your weary heart melt into my chest.")
    time.sleep(5)
    print_centered("Your feelings matter.")
    time.sleep(3)
    print_centered("You are not alone.")
    time.sleep(5)
    print("")
    print_centered("You are are strong, courageous, unyielding, and beautiful.")
    time.sleep(4)
    print_centered("You are loved far beyond your comprehension.")
    time.sleep(3)
    print_centered("You are evidence of God's wonderful visions for all.")
    time.sleep(3)
    print_centered("For the world needed a reason to have hope.")
    time.sleep(3)
    print_centered("So, you were placed.")
    print("")
    time.sleep(5)
    print_centered("As life becomes more busy, time away becomes more difficult.")
    time.sleep(4)
    print_centered("Do not fear. I will not forget about you.")
    time.sleep(3)
    print_centered("You are my 'why,' you are my treasure.")
    time.sleep(4)
    print_centered("I want you to continue life in happiness.")
    time.sleep(3)
    print_centered("I have no intention in you worrying about me if we're away.")
    time.sleep(4)
    print_centered("In times where we cannot interact, remember my pledge to remain with you.")
    time.sleep(4)
    print_centered("So please, don't fear.")
    time.sleep(3)
    print_centered("I remain with you.")
    time.sleep(3)
    print_centered("Borders don't hold my love back from you.")
    time.sleep(3)
    print_centered("Borders couldn't hold me back clearly.")
    print("")
    time.sleep(5)
    print_centered("There will be times when bonds are tested.")
    time.sleep(3)
    print_centered("There will be times when it seems far easier to quit.")
    time.sleep(3)
    print_centered("There will be times when being yourself seems heavy.")
    time.sleep(4)
    print_centered("You will be reminded of why God has another home for us.")
    time.sleep(4)
    print_centered("And that's okay.")
    time.sleep(3)
    print_centered("Sometimes we forget how much we are loved.")
    time.sleep(3)
    print_centered("We often feel that we can carry the burdens by ourselves.")
    time.sleep(4)
    print_centered("Yet, we still fall.")
    time.sleep(3)
    print_centered("And that's okay too.")
    time.sleep(3)
    print_centered("We're all like that, nothing to be ashamed for it.")
    time.sleep(3)
    print_centered("But I must remind you now, that you do not need to hold back your heart from me.")
    time.sleep(5)
    print_centered("You do not have to pretend around me.")
    time.sleep(3)
    print_centered("Show me the side you proclaim is boring.")
    time.sleep(3)
    print_centered("A natural face is true beauty.")
    time.sleep(3)
    print_centered("So please, don't cover yourself up.")
    time.sleep(3)
    print_centered("Let yourself loose around me, feel free to fill in the spaces.")
    time.sleep(4)
    print_centered("I pledge to remain with you, so what I write of should be my formal declaration.")
    time.sleep(4)
    print_centered("You are loved.")




message()
